services:
  fineract:
    image: apache/fineract:3aa011b32
    ports:
      - "8000:8080"
    environment:
      - FINERACT_SERVER_PORT=8000
      - FINERACT_SERVER_SSL_ENABLED=false
      - FINERACT_HIKARI_DRIVER_SOURCE_CLASS_NAME=org.postgresql.Driver
      - FINERACT_HIKARI_JDBC_URL=jdbc:postgresql://db:5432/fineract_tenants
      - FINERACT_HIKARI_USERNAME=postgres
      - FINERACT_HIKARI_PASSWORD=local_password
          # NOTE: env vars prefixed "FINERACT_DEFAULT_TENANTDB_*" are used to create the default tenant database
      - FINERACT_DEFAULT_TENANTDB_HOSTNAME=db
      - FINERACT_DEFAULT_TENANTDB_PORT=5432
      - FINERACT_DEFAULT_TENANTDB_UID=postgres
      - FINERACT_DEFAULT_TENANTDB_PWD=local_password
      - FINERACT_DEFAULT_TENANTDB_CONN_PARAMS=""
      - FINERACT_DEFAULT_TENANTDB_TIMEZONE=Asia/Kolkata
      - FINERACT_DEFAULT_TENANTDB_IDENTIFIER=default
      - FINERACT_DEFAULT_TENANTDB_NAME=fineract_default
      - FINERACT_DEFAULT_TENANTDB_DESCRIPTION=DefaultSyndikizaTenant
      - JAVA_TOOL_OPTIONS=-Xmx1G
    depends_on:
      - db
  
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local_password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
  

  mifos-ui:
    image: openmf/community-app:latest
    ports:
      - "3000:80"

volumes:
  db_data: